# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba83e8fe24d8496653069f8935a4b2e891c85a2db3440d5229cf309f5b3b0c8f94c806ce7e2d6e96725b5454b33e41e8afcc63666717eec9ec08b8a21fee1dc2

test:
  secret_key_base: bd22c9df71ef47d7010d05708e22aa83c563bd0e75b31d93c95ef123fa965626667ddc2f9221c57a956749a6e62d8d300e69c148611b0a986101ade8924c84a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
